title: anadh
email: andrewadhikari2016@gmail.com
description: "A simple and clean jekyll theme."
twitter_username: itbud
github_username:  t-rhex
baseurl: /portfolio
url: "https://t-rhex.github.io"
paginate: 5
paginate_path: "/portfolio/page:num/"
plugins: [jekyll-paginate]

markdown: kramdown
sass:
  sass_dir: _sass
  style: :compressed
theme: wead